set MSDEVDIR=C:\Program Files\DevStudio\SharedIDE
set MSVCDIR=C:\Program Files\DevStudio\VC
set INCLUDE=%MSVCDIR%\INCLUDE;%MSVCDIR%\MFC\INCLUDE;%MSVCDIR%\ATL\INCLUDE;
set LIB=%MSVCDIR%\LIB;%MSVCDIR%\MFC\LIB
set PATH="%MSDEVDIR%\BIN;%MSVCDIR%\BIN;%MSVCDIR%\BIN\WIN95";%PATH%
